# Generated by Django 5.1.6 on 2025-02-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='api.land'),
            preserve_default=False,
        ),
    ]
