# Generated by Django 5.1.6 on 2025-02-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_user_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_land',
        ),
    ]
