# Generated by Django 5.1.6 on 2025-02-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='farm_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='farm_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
