# Generated by Django 5.1.6 on 2025-02-28 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_user_land'),
        ('api', '0002_land_farm_name_land_farm_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='land_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
            preserve_default=False,
        ),
    ]
