# Generated by Django 5.1.6 on 2025-05-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_land_land_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the specific area', max_length=255)),
                ('primary_crop', models.CharField(blank=True, help_text='Primary crop(s) grown', max_length=255, null=True)),
                ('secondary_crops', models.CharField(blank=True, help_text='Secondary crop(s) grown', max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, help_text='Type of soil (Clay, Sandy, Loam, etc.)', max_length=255, null=True)),
                ('irrigation_system', models.CharField(blank=True, help_text='Irrigation method(s) used', max_length=255, null=True)),
                ('fertilizers', models.CharField(blank=True, help_text='Types of fertilizers used', max_length=255, null=True)),
                ('fertilization_frequency', models.CharField(blank=True, help_text='How often fertilizers are applied', max_length=255, null=True)),
                ('fertilization_method', models.CharField(blank=True, help_text='Method of fertilizer application', max_length=255, null=True)),
                ('common_pests', models.CharField(blank=True, help_text='Common pests and diseases', max_length=255, null=True)),
                ('pesticides', models.CharField(blank=True, help_text='Pesticides/fungicides used', max_length=255, null=True)),
                ('previous_yield', models.CharField(blank=True, help_text="Previous season's yield data", max_length=255, null=True)),
                ('soil_test_results', models.CharField(blank=True, help_text='Recent soil test results', max_length=255, null=True)),
                ('yield_losses', models.TextField(blank=True, help_text='Information about recent yield losses', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional observations or comments', null=True)),
                ('soil_reports_path', models.CharField(blank=True, help_text='Path to soil test report files', max_length=500, null=True)),
                ('yield_data_path', models.CharField(blank=True, help_text='Path to yield data files', max_length=500, null=True)),
                ('crop_photos_path', models.CharField(blank=True, help_text='Path to crop/field photos', max_length=500, null=True)),
                ('other_documents_path', models.CharField(blank=True, help_text='Path to other document files', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_details', to='api.land')),
            ],
            options={
                'verbose_name': 'Area Details',
                'verbose_name_plural': 'Area Details',
                'db_table': 'area_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
