# Generated by Django 5.1.6 on 2025-05-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_areadetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the specific area within the land/farm', max_length=255)),
                ('primary_crop', models.CharField(blank=True, help_text='e.g., Wheat, Corn, Rice', max_length=255, null=True)),
                ('secondary_crops', models.TextField(blank=True, help_text='e.g., Soybeans, Vegetables (comma-separated or JSON)', null=True)),
                ('soil_type', models.CharField(blank=True, help_text='e.g., Clay, Sandy, Loam', max_length=100, null=True)),
                ('irrigation_system', models.CharField(blank=True, help_text='e.g., Drip, Sprinkler, Flood', max_length=255, null=True)),
                ('fertilizers', models.TextField(blank=True, help_text='Types of fertilizers used, e.g., NPK, Urea, Organic', null=True)),
                ('fertilization_frequency', models.CharField(blank=True, help_text='e.g., Once per season, Monthly', max_length=100, null=True)),
                ('fertilization_method', models.CharField(blank=True, help_text='e.g., Broadcast, Foliar spray', max_length=100, null=True)),
                ('common_pests', models.TextField(blank=True, help_text='Common pests/diseases, e.g., Aphids, Rust, Blight', null=True)),
                ('pesticides', models.TextField(blank=True, help_text='Pesticides/fungicides used, e.g., Neem oil, Commercial products', null=True)),
                ('previous_yield', models.TextField(blank=True, help_text='e.g., 5 tons/hectare of wheat', null=True)),
                ('soil_test_results_summary', models.TextField(blank=True, help_text='Summary of soil test results, e.g., pH 6.5, High K, Low P', null=True)),
                ('yield_losses_notes', models.TextField(blank=True, help_text='Notes on recent yield losses, e.g., 20% loss due to drought in 2022', null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('soil_reports_file', models.FileField(blank=True, null=True, upload_to='area_documents/soil_reports/')),
                ('yield_data_file', models.FileField(blank=True, null=True, upload_to='area_documents/yield_data/')),
                ('crop_photos_1', models.ImageField(blank=True, null=True, upload_to='area_documents/crop_photos/')),
                ('crop_photos_2', models.ImageField(blank=True, null=True, upload_to='area_documents/crop_photos/')),
                ('other_documents_file', models.FileField(blank=True, null=True, upload_to='area_documents/other_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_details', to='api.land')),
            ],
            options={
                'db_table': 'area_detail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AreaDetails',
        ),
    ]
