# Generated by Django 5.1.6 on 2025-05-26 09:47

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_user_land'),
        ('api', '0005_areadetail_delete_areadetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_crop', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_crops', models.CharField(blank=True, max_length=255, null=True)),
                ('irrigation_system', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilizers', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilization_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('fertilization_method', models.CharField(blank=True, max_length=255, null=True)),
                ('common_pests', models.CharField(blank=True, max_length=255, null=True)),
                ('pesticides', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_yield', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_test_results', models.CharField(blank=True, max_length=500, null=True)),
                ('yield_losses', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_areas', to='account.profile')),
            ],
            options={
                'db_table': 'farm_areas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('soil_reports', 'Soil Test Reports'), ('yield_data', 'Yield Data Sheets'), ('crop_photos', 'Crop/Field Photos'), ('other_documents', 'Other Documents')], max_length=20)),
                ('file', models.FileField(upload_to=api.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('farm_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.farmarea')),
            ],
            options={
                'db_table': 'farm_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='AreaDetail',
        ),
    ]
