# Generated by Django 5.1.6 on 2025-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_farmarea_farmdocument_delete_areadetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmarea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Farm Area', 'verbose_name_plural': 'Farm Areas'},
        ),
        migrations.AlterModelOptions(
            name='farmdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Farm Document', 'verbose_name_plural': 'Farm Documents'},
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional observations or comments', null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='common_pests',
            field=models.CharField(blank=True, help_text='Common pests and diseases', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='fertilization_frequency',
            field=models.CharField(blank=True, help_text='How often fertilizers are applied', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='fertilization_method',
            field=models.CharField(blank=True, help_text='Method of fertilizer application', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='fertilizers',
            field=models.CharField(blank=True, help_text='Types of fertilizers used', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='irrigation_system',
            field=models.CharField(blank=True, help_text='Irrigation method(s) used', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='name',
            field=models.CharField(default=1, help_text='Name of the specific area', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='pesticides',
            field=models.CharField(blank=True, help_text='Pesticides/fungicides used', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='previous_yield',
            field=models.CharField(blank=True, help_text="Previous season's yield data", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='primary_crop',
            field=models.CharField(blank=True, help_text='Primary crop(s) grown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='secondary_crops',
            field=models.CharField(blank=True, help_text='Secondary crop(s) grown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='soil_test_results',
            field=models.CharField(blank=True, help_text='Recent soil test results', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Type of soil (Clay, Sandy, Loam, etc.)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmarea',
            name='yield_losses',
            field=models.TextField(blank=True, help_text='Information about recent yield losses', null=True),
        ),
    ]
