# Generated by Django 5.1.6 on 2025-05-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_farmarea_options_alter_farmdocument_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmarea',
            old_name='additional_notes',
            new_name='additionalNotes',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='common_pests',
            new_name='commonPests',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='fertilization_frequency',
            new_name='fertilizationFrequency',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='fertilization_method',
            new_name='fertilizationMethod',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='irrigation_system',
            new_name='irrigationSystem',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='previous_yield',
            new_name='previousYield',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='primary_crop',
            new_name='primaryCrop',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='secondary_crops',
            new_name='secondaryCrops',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='soil_test_results',
            new_name='soilTestResults',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='soil_type',
            new_name='soilType',
        ),
        migrations.RenameField(
            model_name='farmarea',
            old_name='yield_losses',
            new_name='yieldLosses',
        ),
    ]
