# Generated by Django 5.1.6 on 2025-05-29 18:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_additional_notes_farmarea_additionalnotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmarea',
            name='cropPhotos',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='farmarea',
            name='otherDocuments',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='farmarea',
            name='soilReports',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='farmarea',
            name='yieldData',
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.DeleteModel(
            name='FarmDocument',
        ),
    ]
