# Generated by Django 5.1.6 on 2025-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_farmarea_cropphotos_farmarea_otherdocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmarea',
            name='area_coordinates',
            field=models.JSONField(blank=True, help_text='Area coordinates on the map', null=True),
        ),
        migrations.AddField(
            model_name='farmarea',
            name='center_coordinates',
            field=models.JSONField(blank=True, help_text='Center point of the area', null=True),
        ),
    ]
